version: '3.9'
services:
  postgresql:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: raceputin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: guacatables
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data